spring:
  kafka:
    bootstrap-servers: 172.150.15.36:9092
    ##    zookeeper: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    ##      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    ##      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    #    listener:
    #      type: single
    ##      ack-mode: manual
    consumer:
      ##      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      ##      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-poll-records: 30
      group-id: felix-group
#    listener:
#      type: batch
#      ack-mode: manual

##spring.kafka.bootstrap-servers=172.150.15.36:9092
##spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
##spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#
##spring:
##  kafka:
##    bootstrap-servers: 172.150.15.36:9092
##    producer:
##      key-serializer: org.apache.kafka.common.serialization.StringSerializer
##      value-serializer: org.apache.kafka.common.serialization.StringSerializer
##    consumer:
##      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#spring:
#  kafka:
#    bootstrap-servers: 172.150.15.36:9092
#    producer:
#      retries: 3
#      batch-size: 16384
#      buffer-memory: 33554432
#      acks: 1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: default-group
#      enable-auto-commit: false
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-poll-records: 500
#
#    listener:
#      # 当每⼀条记录被消费者监听器（ListenerConsumer）处理之后提交
#      # RECORD
#      # 当每⼀批poll()的数据被消费者监听器（ListenerConsumer）处理之后提交
#      # BATCH
#      # 当每⼀批poll()的数据被消费者监听器（ListenerConsumer）处理之后，距离上
#      # 次提交时间⼤于TIME时提交
#      # TIME
#      # 当每⼀批poll()的数据被消费者监听器（ListenerConsumer）处理之后，被处理
#      # record数量⼤于等于COUNT时提交
#      # COUNT
#      # TIME | COUNT　有⼀个条件满⾜时提交
#      # COUNT_TIME
#      # 当每⼀批poll()的数据被消费者监听器（ListenerConsumer）处理之后, ⼿动调
#      # ⽤Acknowledgment.acknowledge()后提交
#      # MANUAL
#      # ⼿动调⽤Acknowledgment.acknowledge()后⽴即提交，⼀般使⽤这种
#      # MANUAL_IMMEDIATE
#      ack-mode: MANUAL_IMMEDIATE
#      type: batch