// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserBuf.proto

package com.sq.protobuf;

public final class UserProtobuf {
  private UserProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserBufOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string username = 2;
    /**
     * <code>required string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 2;</code>
     */
    String getUsername();
    /**
     * <code>required string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 3;
    /**
     * <code>required string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 3;</code>
     */
    String getPassword();
    /**
     * <code>required string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional .protobuf.UserBuf.Address address = 4;
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    com.sq.protobuf.UserProtobuf.UserBuf.Address getAddress();
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.UserBuf}
   */
  public static final class UserBuf extends
      com.google.protobuf.GeneratedMessage
      implements UserBufOrBuilder {
    // Use UserBuf.newBuilder() to construct.
    private UserBuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserBuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserBuf defaultInstance;
    public static UserBuf getDefaultInstance() {
      return defaultInstance;
    }

    public UserBuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              username_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
            case 34: {
              com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.sq.protobuf.UserProtobuf.UserBuf.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_protobuf_UserBuf_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_protobuf_UserBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sq.protobuf.UserProtobuf.UserBuf.class, com.sq.protobuf.UserProtobuf.UserBuf.Builder.class);
    }

    public static com.google.protobuf.Parser<UserBuf> PARSER =
        new com.google.protobuf.AbstractParser<UserBuf>() {
      public UserBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserBuf(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UserBuf> getParserForType() {
      return PARSER;
    }

    public interface AddressOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string receiver = 1;
      /**
       * <code>required string receiver = 1;</code>
       */
      boolean hasReceiver();
      /**
       * <code>required string receiver = 1;</code>
       */
      String getReceiver();
      /**
       * <code>required string receiver = 1;</code>
       */
      com.google.protobuf.ByteString
          getReceiverBytes();

      // required string phoneNum = 2;
      /**
       * <code>required string phoneNum = 2;</code>
       */
      boolean hasPhoneNum();
      /**
       * <code>required string phoneNum = 2;</code>
       */
      String getPhoneNum();
      /**
       * <code>required string phoneNum = 2;</code>
       */
      com.google.protobuf.ByteString
          getPhoneNumBytes();
    }
    /**
     * Protobuf type {@code protobuf.UserBuf.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessage
        implements AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Address defaultInstance;
      public static Address getDefaultInstance() {
        return defaultInstance;
      }

      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                receiver_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                phoneNum_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_protobuf_UserBuf_Address_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_protobuf_UserBuf_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sq.protobuf.UserProtobuf.UserBuf.Address.class, com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder.class);
      }

      public static com.google.protobuf.Parser<Address> PARSER =
          new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string receiver = 1;
      public static final int RECEIVER_FIELD_NUMBER = 1;
      private Object receiver_;
      /**
       * <code>required string receiver = 1;</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string receiver = 1;</code>
       */
      public String getReceiver() {
        Object ref = receiver_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiver_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string receiver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string phoneNum = 2;
      public static final int PHONENUM_FIELD_NUMBER = 2;
      private Object phoneNum_;
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public boolean hasPhoneNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public String getPhoneNum() {
        Object ref = phoneNum_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phoneNum_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumBytes() {
        Object ref = phoneNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phoneNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        receiver_ = "";
        phoneNum_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasReceiver()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPhoneNum()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getReceiverBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPhoneNumBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getReceiverBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPhoneNumBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.sq.protobuf.UserProtobuf.UserBuf.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.sq.protobuf.UserProtobuf.UserBuf.Address prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.UserBuf.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return internal_static_protobuf_UserBuf_Address_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return internal_static_protobuf_UserBuf_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.sq.protobuf.UserProtobuf.UserBuf.Address.class, com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder.class);
        }

        // Construct using com.sq.protobuf.UserProtobuf.UserBuf.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          receiver_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          phoneNum_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return internal_static_protobuf_UserBuf_Address_descriptor;
        }

        public com.sq.protobuf.UserProtobuf.UserBuf.Address getDefaultInstanceForType() {
          return getDefaultInstance();
        }

        public com.sq.protobuf.UserProtobuf.UserBuf.Address build() {
          com.sq.protobuf.UserProtobuf.UserBuf.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.sq.protobuf.UserProtobuf.UserBuf.Address buildPartial() {
          com.sq.protobuf.UserProtobuf.UserBuf.Address result = new com.sq.protobuf.UserProtobuf.UserBuf.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.receiver_ = receiver_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.phoneNum_ = phoneNum_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.sq.protobuf.UserProtobuf.UserBuf.Address) {
            return mergeFrom((com.sq.protobuf.UserProtobuf.UserBuf.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.sq.protobuf.UserProtobuf.UserBuf.Address other) {
          if (other == getDefaultInstance()) return this;
          if (other.hasReceiver()) {
            bitField0_ |= 0x00000001;
            receiver_ = other.receiver_;
            onChanged();
          }
          if (other.hasPhoneNum()) {
            bitField0_ |= 0x00000002;
            phoneNum_ = other.phoneNum_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasReceiver()) {
            
            return false;
          }
          if (!hasPhoneNum()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.sq.protobuf.UserProtobuf.UserBuf.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.sq.protobuf.UserProtobuf.UserBuf.Address) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string receiver = 1;
        private Object receiver_ = "";
        /**
         * <code>required string receiver = 1;</code>
         */
        public boolean hasReceiver() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string receiver = 1;</code>
         */
        public String getReceiver() {
          Object ref = receiver_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            receiver_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string receiver = 1;</code>
         */
        public com.google.protobuf.ByteString
            getReceiverBytes() {
          Object ref = receiver_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            receiver_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string receiver = 1;</code>
         */
        public Builder setReceiver(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          receiver_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string receiver = 1;</code>
         */
        public Builder clearReceiver() {
          bitField0_ = (bitField0_ & ~0x00000001);
          receiver_ = getDefaultInstance().getReceiver();
          onChanged();
          return this;
        }
        /**
         * <code>required string receiver = 1;</code>
         */
        public Builder setReceiverBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          receiver_ = value;
          onChanged();
          return this;
        }

        // required string phoneNum = 2;
        private Object phoneNum_ = "";
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public boolean hasPhoneNum() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public String getPhoneNum() {
          Object ref = phoneNum_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            phoneNum_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPhoneNumBytes() {
          Object ref = phoneNum_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            phoneNum_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public Builder setPhoneNum(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          phoneNum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public Builder clearPhoneNum() {
          bitField0_ = (bitField0_ & ~0x00000002);
          phoneNum_ = getDefaultInstance().getPhoneNum();
          onChanged();
          return this;
        }
        /**
         * <code>required string phoneNum = 2;</code>
         */
        public Builder setPhoneNumBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          phoneNum_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobuf.UserBuf.Address)
      }

      static {
        defaultInstance = new Address(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobuf.UserBuf.Address)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string username = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private Object username_;
    /**
     * <code>required string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string username = 2;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private Object password_;
    /**
     * <code>required string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string password = 3;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .protobuf.UserBuf.Address address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.sq.protobuf.UserProtobuf.UserBuf.Address address_;
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    public com.sq.protobuf.UserProtobuf.UserBuf.Address getAddress() {
      return address_;
    }
    /**
     * <code>optional .protobuf.UserBuf.Address address = 4;</code>
     */
    public com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder getAddressOrBuilder() {
      return address_;
    }

    private void initFields() {
      id_ = 0;
      username_ = "";
      password_ = "";
      address_ = com.sq.protobuf.UserProtobuf.UserBuf.Address.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddress()) {
        if (!getAddress().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, address_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sq.protobuf.UserProtobuf.UserBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sq.protobuf.UserProtobuf.UserBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.UserBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sq.protobuf.UserProtobuf.UserBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_protobuf_UserBuf_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_protobuf_UserBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sq.protobuf.UserProtobuf.UserBuf.class, com.sq.protobuf.UserProtobuf.UserBuf.Builder.class);
      }

      // Construct using com.sq.protobuf.UserProtobuf.UserBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (addressBuilder_ == null) {
          address_ = com.sq.protobuf.UserProtobuf.UserBuf.Address.getDefaultInstance();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_protobuf_UserBuf_descriptor;
      }

      public com.sq.protobuf.UserProtobuf.UserBuf getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.sq.protobuf.UserProtobuf.UserBuf build() {
        com.sq.protobuf.UserProtobuf.UserBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sq.protobuf.UserProtobuf.UserBuf buildPartial() {
        com.sq.protobuf.UserProtobuf.UserBuf result = new com.sq.protobuf.UserProtobuf.UserBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sq.protobuf.UserProtobuf.UserBuf) {
          return mergeFrom((com.sq.protobuf.UserProtobuf.UserBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sq.protobuf.UserProtobuf.UserBuf other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sq.protobuf.UserProtobuf.UserBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sq.protobuf.UserProtobuf.UserBuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string username = 2;
      private Object username_ = "";
      /**
       * <code>required string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string username = 2;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 3;
      private Object password_ = "";
      /**
       * <code>required string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string password = 3;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      // optional .protobuf.UserBuf.Address address = 4;
      private com.sq.protobuf.UserProtobuf.UserBuf.Address address_ = com.sq.protobuf.UserProtobuf.UserBuf.Address.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sq.protobuf.UserProtobuf.UserBuf.Address, com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder, com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public com.sq.protobuf.UserProtobuf.UserBuf.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public Builder setAddress(com.sq.protobuf.UserProtobuf.UserBuf.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public Builder setAddress(
          com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public Builder mergeAddress(com.sq.protobuf.UserProtobuf.UserBuf.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              address_ != com.sq.protobuf.UserProtobuf.UserBuf.Address.getDefaultInstance()) {
            address_ =
              com.sq.protobuf.UserProtobuf.UserBuf.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = com.sq.protobuf.UserProtobuf.UserBuf.Address.getDefaultInstance();
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      public com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_;
        }
      }
      /**
       * <code>optional .protobuf.UserBuf.Address address = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.sq.protobuf.UserProtobuf.UserBuf.Address, com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder, com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sq.protobuf.UserProtobuf.UserBuf.Address, com.sq.protobuf.UserProtobuf.UserBuf.Address.Builder, com.sq.protobuf.UserProtobuf.UserBuf.AddressOrBuilder>(
                  address_,
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.UserBuf)
    }

    static {
      defaultInstance = new UserBuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.UserBuf)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_UserBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_UserBuf_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_UserBuf_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_UserBuf_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rUserBuf.proto\022\010protobuf\"\224\001\n\007UserBuf\022\n\n" +
      "\002id\030\001 \002(\005\022\020\n\010username\030\002 \002(\t\022\020\n\010password\030" +
      "\003 \002(\t\022*\n\007address\030\004 \001(\0132\031.protobuf.UserBu" +
      "f.Address\032-\n\007Address\022\020\n\010receiver\030\001 \002(\t\022\020" +
      "\n\010phoneNum\030\002 \002(\tB\037\n\017com.sq.protobufB\014Use" +
      "rProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_UserBuf_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_UserBuf_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_UserBuf_descriptor,
              new String[] { "Id", "Username", "Password", "Address", });
          internal_static_protobuf_UserBuf_Address_descriptor =
            internal_static_protobuf_UserBuf_descriptor.getNestedTypes().get(0);
          internal_static_protobuf_UserBuf_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_UserBuf_Address_descriptor,
              new String[] { "Receiver", "PhoneNum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
