#spring:
#  application:
#    name: auth-server
#
#redis:
##  database: 2
#  host: localhost
#  port: 6379
#  password:
#  jedis:
#    pool:
#      max-active: 8
#      max-idle: 8
#      min-idle: 0
#      timeout: 100ms
#
#server:
#  port: 6001
#
#management:
#  endpoint:
#    health:
#      enabled: true

spring:
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
